### ISSUE TITLE
work with file on server?

### ISSUE THREAD

**Issue by yuomtheara** [matteodem/meteor-boilerplate#70]
I would like to work with fiel like `read`, `write`, `remove` .... on server.
Have any package to do for meteor?

**Comment by matteodem** [comment]
Please have in mind that meteor is essentially a big wrapper around node on the server side. So it's possible to use all of https://www.npmjs.com/ + http://nodejs.org/api/. https://www.meteor.com/blog/2013/04/04/meteor-060-brand-new-distribution-system-app-packages-npm-integration.

Please don't ask such questions before having a look for yourself, since this are things that are pretty clearly stated on their docs.

**Comment by yuomtheara** [comment]
Sorry, because I am new for `meteor` (I come from Laravel PHP Framework).

**Comment by matteodem** [comment]
It's fine, just searching right might help you more sometimes.
