### ISSUE TITLE
Restructure Boilerplate

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-boilerplate#99]
With 1.3 we finally get a way to write modular code by importing / exporting code and having manageable scopes. Try to restructure the boilerplate with that fact  and rethink other parts of the boilerplate.

* Use import / export functionality + change boilerplate structure
* Switch out iron-router with flow-router
* Have a look at blaze-like alternatives? blaze components, side burns

**Comment by zorrobyte** [comment]
No thanks to switching out iron-router in my opinion. Fork it instead as most learning resources aren't updated for flow-router and for a newbie like me moving from Django, I've almost gave up on Meteor due to the clusterfrack of confusing resources.

**Comment by matteodem** [comment]
Of course it is, but using iron-router is rather simple. You'll still have the orion-cli tool. Please show me which learning resources you're referring to. The Meteor Guide, which should be your go to docs for advanced meteor, [use iron-router](http://guide.meteor.com/routing.html) and the basic meteor docs don't cover routing techniques.

**Comment by Laurentiu-Andronache** [comment]
Iron Router is the complete solution. It's better.

**Comment by matteodem** [comment]
Please give at least arguments that prove your point. The meteor guide is still using flow router as it's router and how I see it, it's a very lean implementation which makes sense in the meteor world where state should be managed in your templates / components and not the router.

**Comment by Laurentiu-Andronache** [comment]
The argument was that it's a complete solution. With flow router, you'll usually end up installing other packages as well related to layouts, rendering and so on. Now I know this ain't a strong argument because running a few installs is not a big deal. It makes it a bit harder to master though.

Related to this: "the meteor world where state should be managed in your templates / components". Pff... you're right. I forgot about that, it was bugging me as well. Can we just ignore my initial post and move on, I don't want to debate because I think I'll lose.

**Comment by matteodem** [comment]
It's fine, I know that iron-router just seems more stable and fully-fledged, but based on the open issues and other folks that use Meteor flow-router seems to provide a more modern approach to all of this.

Also this boilerplate will include the blaze render layout package so that you don't need to worry about that.
